### ISSUE TITLE
哪一个版本支持thinkphp5.1的呢？

### ISSUE THREAD

**Issue by lxmwuchao1314** [top-think/think-throttle#12]
![image](https://user-images.githubusercontent.com/45166702/133566031-a6b473d8-5a76-41d8-8b43-92a708835b5d.png)

**Comment by hongweipeng** [comment]
没有适配 thinkphp5.1

**Comment by daidaiworm** [comment]
很需要整个功能呢，能否适配一下5.1呢

**Comment by hongweipeng** [comment]
调试了一个版本 `0.5.0` 适配 tp 5.1 ，可以试下。
