### ISSUE TITLE
缓存键的缓存时间是否是过于太久了

### ISSUE THREAD

**Issue by 18215569765** [top-think/think-throttle#14]
缓存键的缓存时间是否是过于太久了

**Comment by hongweipeng** [comment]
缓存的时间是根据配置来的，比如 `'visit_rate' => '100/m'` 那么缓存时间就是 1 分钟。

**Comment by 18215569765** [comment]
我设置的10/3
![image](https://user-images.githubusercontent.com/55829329/142589509-37bf1877-2287-4d14-ba7b-f79f49d8d091.png)
缓存时间会很长
