### ISSUE TITLE
composer安装之后的版本还是0.1.0

### ISSUE THREAD

**Issue by itxq** [top-think/think-throttle#3]

**Comment by hongweipeng** [comment]
@liu21st 能否同步下 `https://packagist.org/packages/topthink/think-throttle` ，tag我已经打好了。

@itxq 当前，您可以尝试用 `composer require topthink/think-throttle dev-master` 来安装master分支。

**Comment by liu21st** [comment]
应该是自动同步的 我看了下 应该是你的composer.json 有问题，
"topthink/framework": "^6.0.*" 这个写法有问题

**Comment by hongweipeng** [comment]
还真是，改好了。感谢。
