### ISSUE TITLE
使用路由方式__CONTROLLER__/__ACTION__/__IP__不显示了 

### ISSUE THREAD

**Issue by dj8jj** [top-think/think-throttle#34]
Route::group(function (){
    Route::get('journal/:id',"index/Journal/details");
})->middleware(\think\middleware\Throttle::class, [
    'visit_rate' => '20/m',
    'key' => '__CONTROLLER__/__ACTION__/__IP__',
]);

 'key' => '__CONTROLLER__/__ACTION__/__IP__',
这个不起作用啊！什么信息都没有！
只显示一个Too Many Requests

**Comment by hongweipeng** [comment]
全局中间件有去掉吗

**Comment by dj8jj** [comment]
![微信截图_20231219162708](https://github.com/top-think/think-throttle/assets/55225813/98f1df66-25c7-4388-82d0-f6d01299be33)
是不是指这个，我有加上啊！
然后路由我是这样的
![微信截图_20231219162814](https://github.com/top-think/think-throttle/assets/55225813/c2d0c956-465b-4601-8676-ecb1cd3f8e8f)

**Comment by dj8jj** [comment]
然后显示只能显示文字部分，那个key部分无显示。
![微信截图_20231219163010](https://github.com/top-think/think-throttle/assets/55225813/434ddec4-d314-40b1-8d3d-00e62e9a443e)

**Comment by dj8jj** [comment]
我是thinkphp8框架

**Comment by dj8jj** [comment]
> 全局中间件有去掉吗

麻烦帮忙看下，哪里配置问题了

**Comment by hongweipeng** [comment]
![image](https://github.com/top-think/think-throttle/assets/7546325/ebc4a11f-99d2-410b-ad20-78bc5f2e6769)

这个要去掉

**Comment by hongweipeng** [comment]
如果全局中间件和路由中间件都用的话，会走两遍频率限制中间件的。

**Comment by dj8jj** [comment]
> ![image](https://private-user-images.githubusercontent.com/7546325/291547862-ebc4a11f-99d2-410b-ad20-78bc5f2e6769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzMzODYsIm5iZiI6MTcwMzAzMzA4NiwicGF0aCI6Ii83NTQ2MzI1LzI5MTU0Nzg2Mi1lYmM0YTExZi05OWQyLTQxMGItYWQyMC03OGJjNWYyZTY3NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDA0NDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzEyNmY2Mjk4MTc4NDE5ODE2MWQ0NmEzNmVkN2QxMzMzNzJjNjdlMWVhMGYwYmM2OGE4NGE0OTYzNmMxNWM5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cYshgjqqgp8ACcVWIS7oPeLV78ncOdr__nEMh3D1Y54)
> 
> 这个要去掉

去掉了 也一样的！ key不显示

**Comment by hongweipeng** [comment]
![image](https://github.com/top-think/think-throttle/assets/7546325/ca3472f8-7603-4576-bd68-34ed3d6047b5)

看着 key 是没问题的。你那个”对不起！请求过于频繁...” 的页面是这个插件返回的吗？

**Comment by dj8jj** [comment]
> ![image](https://private-user-images.githubusercontent.com/7546325/291764875-ca3472f8-7603-4576-bd68-34ed3d6047b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDg4MTQsIm5iZiI6MTcwMzA0ODUxNCwicGF0aCI6Ii83NTQ2MzI1LzI5MTc2NDg3NS1jYTM0NzJmOC03NjAzLTQ1NzYtYmQ2OC0zNGVkM2Q2MDQ3YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDUwMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTYyZjJkNjA4OGM5MDhmNjlmOWZlZDhjNWUzOTVhNjIyNGZkOTRlMzg4NjUyY2RlY2QzMmQ2MmZmZDE4Y2JiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gnaufZ-xDbr2UvQjWjv64Qoo3X72i80nkBPQIUKusOI)
> 
> 看着 key 是没问题的。你那个”对不起！请求过于频繁...” 的页面是这个插件返回的吗？

对啊！！就是你这个插件，我自己加工了一下。
![微信截图_20231220130448](https://github.com/top-think/think-throttle/assets/55225813/3aad511d-423b-47eb-a575-2a3e8586ba5d)

**Comment by dj8jj** [comment]
好了搞定了！我重新加工了一下返回信息。
![微信截图_20231220132140](https://github.com/top-think/think-throttle/assets/55225813/2ee06f2a-8d20-4b8a-84eb-cdcdbccae803)
