### ISSUE TITLE
求大神教教怎么使用呗

### ISSUE THREAD

**Issue by iamssn** [top-think/think-throttle#5]
TP6 想使用这个限流器,限制一个模块中的几个方法.具体到用户和限制次数,应该怎么设置呢?
namespace app\api\controller;

use think\middleware\Throttle;
class Equ extends ApiController
{
    protected $middleware = [Throttle::class];
    /**
     * 查询所有设备
     * @return string
     */
    public function infoAll()
    {
        #获取用户key,查询该用户全部设备
        return 'infoAll';
    }

    /**
     *查询所有设备DID
     * @return string
     */
    public function did()
    {
        return 'did';
    }
}

比如限制这两个函数的访问次数,根据用户的不同,允许访问的次数也不同,有一个小时10次的,有1天100次的.用户数据表中有个字段存了10/m  20/h  300/d  这种信息

应该怎么使用这个功能呢?
求大神指点一下呗.

**Comment by hongweipeng** [comment]
@iamssn 现在控制器中定义 `$middleware` ，上述示例的代码是对的。然后在配置文件中 `config/throttle.php` 可以类似的设置:
```
use think\facade\Db;

return [
    ...
    'key' => function(\think\middleware\Throttle $throttle, $request) {
        $user = DB::name('user')->where('uid', session::get('uid'))->find();
        $throttle->setRate($user['rate']);  // "2/m"
        return true;
    },
    ...
];
```
我的例子是有用到 session 的，需要开启session中间件的。设置的方式就是通过 `$throttle->setRate()` 进行设置的。
