### ISSUE TITLE
算法推荐

### ISSUE THREAD

**Issue by x12311231** [top-think/think-throttle#7]
protected function accessLimit(array $option = []) {
        $limit = [
            'ip' => ['expire' => 10, 'time' => 30, 'times' => 300, 'value' => Request::ip()],//同一ip地址{time}s内超过{times}次,拒绝访问{expire}s
            'userID' => ['expire' => 10, 'time' => 30, 'times' => 100, 'value' => USERID],//同一用户{time}s内超过{times}次,拒绝访问{expire}s
        ];
        $limit = array_merge($limit, $option);
        foreach ($limit as $k => $v) {
            $key1 = RedisManager::makeKeyV1(['MODULE', 'CONTROLLER', 'ACTION', 'OTHER'], [Request::module(), Request::controller(), Request::action(), $v['value']], RedisConfig::String_api_limit_access);
            $access1 = RedisManager::getRedis()->get($key1);
            if ($access1 && $access1 >= $v['times']) {
                if ($access1 > $v['times']) {
                    $leftTime = RedisManager::getRedis()->ttl($key1);
                    RedisManager::getRedis()->setex($key1, $leftTime, (int)$access1);
                } else {
                    RedisManager::getRedis()->setex($key1, $v['expire'], (int)$access1 + 1);
                }
                return false;
            }
            RedisManager::getRedis()->setex($key1, $v['time'], (int)$access1 + 1);
        }
        return true;
    }
}

**Comment by king192** [comment]
protected function accessLimit(array $option = []) {
        $limit = [
            'ip' => ['expire' => 10, 'time' => 30, 'times' => 300, 'value' => Request::ip()],//同一ip地址{time}s内超过{times}次,拒绝访问{expire}s
            'userID' => ['expire' => 10, 'time' => 30, 'times' => 100, 'value' => USERID],//同一用户{time}s内超过{times}次,拒绝访问{expire}s
        ];
        $limit = array_merge($limit, $option);
        foreach ($limit as $k => $v) {
            $key1 = RedisManager::makeKeyV1(['MODULE', 'CONTROLLER', 'ACTION', 'OTHER'], [Request::module(), Request::controller(), Request::action(), $v['value']], RedisConfig::String_api_limit_access);
            $access1 = RedisManager::getRedis()->get($key1);
            if ($access1 && $access1 >= $v['times']) {
                if ($access1 > $v['times']) {
                    $leftTime = RedisManager::getRedis()->ttl($key1);
                    RedisManager::getRedis()->setex($key1, $leftTime, (int)$access1);
                } else {
                    RedisManager::getRedis()->setex($key1, $v['expire'], (int)$access1 + 1);
                }
                return false;
            }
            if (false === $access1) {
                RedisManager::getRedis()->setex($key1, $v['time'], (int)$access1 + 1);
            } else {
                $leftTime = RedisManager::getRedis()->ttl($key1);
                RedisManager::getRedis()->setex($key1, $leftTime, (int)$access1 + 1);
            }
        }
        return true;
    }

**Comment by hongweipeng** [comment]
计数固定窗口和滑动窗口的算法都已经得到支持了
